- src/main/java/com/alkemy/ong/domain/model/Activity.java
- src/main/java/com/alkemy/ong/domain/repository/ActivityRepository.java
- src/main/resources/db/migration/V1.21__create_table_activities.sql
- src/main/resources/db/migration/V1.21__create_table_activity.sql
Quiero agregar la entidad Activity para representar en la implementación la estructura de datos
Criterios de aceptación: 
Nombre de tabla: ~~activities~~ **activity**. Campos:
name: VARCHAR NOT NULL
content: TEXT NOT NULL
image: VARCHAR NOT NULL
timestamps y softDelete
> [OT210-21] Added Activity entity, Activity repository

- src/main/java/com/alkemy/ong/domain/model/Testimonial.java
- src/main/java/com/alkemy/ong/domain/repository/TestimonialRepository.java
- src/main/resources/db/migration/V1.20__create_table_testimonial.sql
> [OT210-20] Crear modelo y repositorio de Testimonials

- src/main/java/com/alkemy/ong/domain/model/Organization.java
- src/main/java/com/alkemy/ong/domain/repository/OrganizationRepository.java
- src/main/resources/application.properties
- src/main/resources/db/migration/V1.15__create_table_organization.sql
COMO desarrollador 
QUIERO agregar la entidad Organization
PARA representar en la implementación la estructura de datos
Criterios de aceptación: 
Nombre de tabla: organizations. Los campos son:
name: VARCHAR NOT NULL
image: VARCHAR NOT NULL
address: VARCHAR NULLABLE
phone: INTEGER NULLABLE
email: VARCHAR NOT NULL
welcomeText: TEXT NOT NULL
aboutUsText: TEXT NULLABLE
timestamps y softDelete
> [OT210-15] Adding Organization Entity, repository and script.

- src/main/java/com/alkemy/ong/domain/usecase/TestimonialService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/TestimonialServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/TestimonialApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/TestimonialController.java
- src/main/java/com/alkemy/ong/ports/input/rs/mapper/TestimonialControllerMapper.java
- src/main/java/com/alkemy/ong/ports/input/rs/request/CreateTestimonialRequest.java
- src/main/resources/application.properties
> [OT210-65] Endpoint de testimonial creado

- src/main/java/com/alkemy/ong/domain/model/Member.java
- src/main/java/com/alkemy/ong/domain/repository/MemberRepository.java
- src/main/resources/db/migration/V1.22__create_table_member.sql
COMO desarrollador 
QUIERO agregar la entidad Member
PARA representar en la implementación la estructura de datos
Criterios de aceptación: 
Nombre de tabla: member. Campos:
name: VARCHAR NOT NULL
facebookUrl: VARCHAR NULLABLE
instagramUrl: VARCHAR NULLABLE
linkedinUrl: VARCHAR NULLABLE
image: VARCHAR NOT NULL
description: VARCHAR NULLABLE
timestamps y softDelete
> [OT210-22] Crear modelo y repositorio de base Members

- src/main/java/com/alkemy/ong/ports/output/email/EmailService.java
- src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
- src/main/resources/application.properties
Descripción
COMO usuario
QUIERO ver un mail de bienvenida cuando me registro
PARA asegurarme que el registro ocurrió correctamente.
Utilizar el servicio de envío de emails y el template de bienvenida para enviar un email de forma programática cuando un usuario se registre, al email que proporcionó en su registro.
Cuando el usuario se registre en el sitio, se enviará un email de bienvenida.
> [OT210-30] Adding Welcome Email

- src/main/java/com/alkemy/ong/domain/usecase/MemberService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/MemberServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/MemberApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/MemberController.java
- src/main/java/com/alkemy/ong/ports/input/rs/mapper/MemberControllerMapper.java
- src/main/java/com/alkemy/ong/ports/input/rs/request/CreateMemberRequest.java
COMO usuario
QUIERO crear un miembro
PARA actualizar la información de la web.
POST /members - Deberá validar que se envíe el campo name, y el mismo sea un string
> [OT210-69] Endpoint creacion miembros

- src/main/java/com/alkemy/ong/configuration/SecurityConfig.java
- src/main/java/com/alkemy/ong/domain/model/UserList.java
- src/main/java/com/alkemy/ong/domain/usecase/UserService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/UserServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/UserApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/AuthController.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/UserController.java
- src/main/java/com/alkemy/ong/ports/input/rs/mapper/UserControllerMapper.java
- src/main/java/com/alkemy/ong/ports/input/rs/response/UserResponse.java
- src/main/java/com/alkemy/ong/ports/input/rs/response/UserResponseList.java
QUIERO visualizar un listado de Usuarios
PARA mantener un seguimiento de quiénes forman parte del sistema
GET a /users . Devolverá un listado de todos los Usuarios. Este endpoint solo deberá ser accesible por los Usuarios administradores.
> [OT210-35] Endpoint para listar Usuarios

- src/main/java/com/alkemy/ong/domain/usecase/CategoryService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/CategoryServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/CategoryApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/CategoryController.java
- src/main/java/com/alkemy/ong/ports/input/rs/mapper/CategoryControllerMapper.java
- src/main/java/com/alkemy/ong/ports/input/rs/request/CreateCategoryRequest.java
QUIERO agregar una categoría nueva al sistema
PARA categorizar las Novedades
POST /categories - Deberá validar que se envíe el campo name, y el mismo sea un string
> [OT210-42] Create Category

- src/main/java/com/alkemy/ong/domain/model/Organization.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/OrganizationServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/request/UpdateOrganizationRequest.java
- src/main/java/com/alkemy/ong/ports/input/rs/response/OrganizationResponse.java
- src/main/resources/db/migration/V1.63__alter_table_organization.sql
Contacts added to Organization attributes
QUIERO editar los campos de contacto a la Organización
PARA mostrar la información de la mejor manera posible. 
Modificar modelo, repositorio y servicio para agregar las urls de redes sociales a una Organización. Se deberán agregar url de Facebook, Linkedin e Instagram
> [OT210-63] Contacts added to Organization attributes

- src/main/java/com/alkemy/ong/domain/usecase/CategoryService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/CategoryServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/CategoryApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/CategoryController.java
- src/main/java/com/alkemy/ong/ports/input/rs/mapper/CategoryControllerMapper.java
- src/main/java/com/alkemy/ong/ports/input/rs/request/CreateCategoryRequest.java
QUIERO eliminar una categoría existente
PARA mantener la información actualizada
DELETE /categories/:id - Deberá validar que la categoría existe y eliminarla.
> [OT210-44] Adding Delete Category

- src/main/resources/db/migration/V1.52__insert_into_table_activity.sql
COMO usuario
QUIERO visualizar los datos existentes de la ONG
PARA mantener la información actualizada
En base a los datos existentes en el caso ONG, crear un seeder que permita popular estos datos en la base (en caso de no utilizar un ORM, generar un script de base de datos).
> [OT210-52] Crear Seed Data para guardar Actividades existentes de la ONG

- src/main/java/com/alkemy/ong/domain/usecase/UserService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/UserServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/UserApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/UserController.java
Descripción
COMO usuario
QUIERO eliminar mi usuario
PARA darme de baja del sistema
DELETE a /users/:id Deberá recibir el id del usuario con el método DELETE. El borrado debe ser lógico.
> [QT210-32] Endpoint Delete User created

- src/main/java/com/alkemy/ong/ports/input/rs/response/OrganizationResponse.java
Descripción
COMO usuario
QUIERO ver los links de las redes sociales al entrar a la página
PARA poder acceder a ellas.
- Al devolver los datos en el endpoint de datos públicos, agregar los campos de redes sociales en la respuesta
> [OT210-64] Organization contacts added to response.

- src/main/java/com/alkemy/ong/configuration/SecurityConfig.java
- src/main/java/com/alkemy/ong/domain/model/Contact.java
- src/main/java/com/alkemy/ong/domain/usecase/ContactService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/ContactServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/ContactApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/ContactController.java
- src/main/java/com/alkemy/ong/ports/input/rs/mapper/ContactControllerMapper.java
- src/main/java/com/alkemy/ong/ports/input/rs/request/CreateContactRequest.java
- src/main/resources/db/migration/V1.54__alter_table_contact.sql
COMO usuario
QUIERO dar de alta contactos
PARA que estén en la base de datos
Se debe hacer una petición POST /contacts 
-Se verificará que la petición contenga los campos name y emailSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
> [OT210-54] Endpoint para almacenar contactos

- src/main/java/com/alkemy/ong/domain/usecase/ActivityService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/ActivityServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/ActivityApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/ActivityController.java
QUIERO actualizar una actividad existente
PARA mantener la información actualizada
PUT /activities/:id - Deberá validar que la actividad exista en base al id enviado por parámetro. En el caso de que no exista devolver un error, caso contrario actualizarla y devolverla con los datos actualizados
> [OT210-51] Endpoint Actualización Actividades

- src/main/java/com/alkemy/ong/domain/model/Comment.java
- src/main/java/com/alkemy/ong/domain/repository/CommentRepository.java
- src/main/java/com/alkemy/ong/domain/usecase/CommentService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/CommentServiceImpl.java
- src/main/resources/db/migration/V1.74__create_table_comment.sql
COMO usuario 
QUIERO agregar un nuevo comentario a una novedad
PARA opinar acerca de dicha novedad
Se agregará la posibilidad de agregar Comments a una Novedad. Los campos de un comentario serán user_id, body y news_id
> [OT210-74] Added Comment model, repository and service

- src/main/java/com/alkemy/ong/domain/usecase/impl/ContactServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/ContactController.java
- src/main/java/com/alkemy/ong/ports/output/email/EmailService.java
- src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
- src/main/resources/application.properties
COMO usuario 
QUIERO recibir un correo cuando me contacto
PARA confirmar que he completado el contacto con éxito.
Cuando se registre un nuevo contacto en el sitio, enviar un email al usuario que completó el formulario agradeciendo su contacto. Para esto, utilizar el servicio de envío de emails.
> [OT210-62] Enviar email de contacto

- src/main/java/com/alkemy/ong/configuration/SecurityConfig.java
- src/main/java/com/alkemy/ong/domain/model/ContactList.java
- src/main/java/com/alkemy/ong/domain/usecase/ContactService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/ContactServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/ContactApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/ContactController.java
- src/main/java/com/alkemy/ong/ports/input/rs/mapper/ContactControllerMapper.java
- src/main/java/com/alkemy/ong/ports/input/rs/response/ContactResponse.java
- src/main/java/com/alkemy/ong/ports/input/rs/response/ContactResponseList.java
QUIERO obtener el listado de contactos
PARA llevar un control de los contactos recibidos.
GET /contacts - Devolverá todos los registros de contactos. Este endpoint solo podrá ser accedido por un usuario administrador.
> [OT210-61] Endpoint para listar contactos (y paginacion)

- src/main/java/com/alkemy/ong/domain/usecase/MemberService.java
- src/main/java/com/alkemy/ong/domain/usecase/UserService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/MemberServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/MemberApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/MemberController.java
Descripción
QUIERO eliminar un miembro
PARA que no sea más parte de la Organización
Criterios de aceptación:DELETE /members/:id - Deberá validar que el miembro existe.
=============================================================================
Creación de un miembro para prueba por Postman
Miembro creado en la base de datos y su estado activo = TRUE
Borrado lógico de un miembro por Postman
Miembro eliminadoen la base de datos y su estado inactivo = FALSE
>  [OT210-70] Endpoint Elimination Members created

- src/main/java/com/alkemy/ong/domain/model/NewList.java
- src/main/java/com/alkemy/ong/domain/usecase/NewService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/NewServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/NewApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/NewController.java
- src/main/java/com/alkemy/ong/ports/input/rs/mapper/NewControllerMapper.java
- src/main/java/com/alkemy/ong/ports/input/rs/response/NewResponse.java
- src/main/java/com/alkemy/ong/ports/input/rs/response/NewResponseList.java
COMO usuario
QUIERO visualizar los resultados de Novedades paginados
PARA aumentar la velocidad de respuesta
Cuando se realice la petición para listar, los resultados deberán paginarse de a 10. En la respuesta, se deberán mostrar los resultados y las urls para la página anterior y siguiente (si corresponden). La página actual se obtendrá del parámetro de query ?page
> [OT210-81] Agregar paginación a Novedades

- src/main/java/com/alkemy/ong/domain/usecase/SlideService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/SlideServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/SlideApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/SlideController.java
- src/main/resources/application.properties
QUIERO poder eliminar Slides 
PARA tener la información actualizada al comienzo de la página
Se debe hacer una petición DELETE /Slides/:id 
Deberá validar que el slide existe y eliminarlo, caso contrario devolver un error
> [OT210-59] Endpoint Eliminacion  Slides

- src/main/java/com/alkemy/ong/domain/usecase/NewService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/NewServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/NewApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/NewController.java
QUIERO eliminar una actividad existente
PARA mantener la información actualizada
DELETE /news/:id - Deberá validar la existencia en base al id enviado por parámetro. En el caso de que exista, eliminarla
> [OT210-48] Endpoint Eliminar Novedades

- src/main/java/com/alkemy/ong/domain/usecase/NewService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/NewServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/NewApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/NewController.java
- src/main/java/com/alkemy/ong/ports/input/rs/mapper/NewControllerMapper.java
QUIERO actualizar una novedad existente
PARA poder mantener a información actualizada
PUT /news/:id - Deberá validar que la novedad exista en base al id enviado por parámetro. En el caso de que no exista devolver un error, caso contrario actualizar la novedad y devolver la misma con los datos actualizados
> [OT210-47] Endpoint Actualizar Novedades

- src/main/java/com/alkemy/ong/ports/input/rs/api/TestimonialApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/TestimonialController.java
- src/main/resources/application.properties
COMO desarrollador
QUIERO disponer de una documentación de los endpoints de Testimonios
PARA tener referencias de su funcionamiento
Se deberán documentar los diferentes endpoints especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.
> [OT210-88] Testimonial Documentation

- src/main/java/com/alkemy/ong/domain/model/CommentList.java
- src/main/java/com/alkemy/ong/domain/usecase/CommentService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/CommentServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/CommentApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/CommentController.java
- src/main/java/com/alkemy/ong/ports/input/rs/mapper/CommentControllerMapper.java
- src/main/java/com/alkemy/ong/ports/input/rs/response/CommentResponse.java
- src/main/java/com/alkemy/ong/ports/input/rs/response/CommentResponseList.java
QUIERO obtener un listado de Comentarios
PARA moderar los mismo.
GET /comments - Devolverá todos los Comentarios, ordenados por fecha de creación, solamente el campo body
> [OT210-75] Endpoint para listar Comentarios

- src/main/java/com/alkemy/ong/ports/input/rs/api/MemberApi.java
Descripción
COMO desarrollador
QUIERO disponer de una documentación de los endpoints de Miembros
PARA tener referencias de su funcionamiento
Se deberán documentar los diferentes endpoints especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.
==============================================================================
Add documentation to Members
> [QT210-87] Add documentation to Members

- src/main/java/com/alkemy/ong/ports/input/rs/response/CategoryResponseList.java
- src/test/java/com/alkemy/ong/ports/input/rs/controller/CategoryControllerIT.java
- src/test/java/com/alkemy/ong/ports/input/rs/controller/CategoryControllerTest.java
COMO desarrollador
QUIERO disponer de tests de los endpoints de /categories
PARA asegurar la integridad y funcionamiento del proyecto
Testear el escenario de respuesta correcta, y escenarios de error, como ids inexistentes, validaciones, permisos, etc. El archivo deberá crearse dentro de la carpeta /test, con el mismo nombre del endpoint. Se puede utilizar como base el test creado a modo de demostración.
> [OT210-97] Adding Category Tests

- src/main/java/com/alkemy/ong/domain/model/Organization.java
- src/main/java/com/alkemy/ong/domain/usecase/OrganizationService.java
- src/main/java/com/alkemy/ong/domain/usecase/impl/OrganizationServiceImpl.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/OrganizationApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/OrganizationController.java
- src/main/java/com/alkemy/ong/ports/input/rs/mapper/OrganizationControllerMapper.java
COMO usuario
QUIERO ver Slides cuando entro a la pagina
PARA estar más informados sobre ellos
En el endpoint de datos públicos de la Organización, se deberán agregar el listado de Slides ordenados por el campo "order". 
Los Slides serán los pertenecientes a la Organización, en base al campo organization_id que deberá corresponder a la Organización que se está devolviendo
> [OT210-60] Agregar Slides a Endpoint publico

- src/main/java/com/alkemy/ong/configuration/SecurityConfig.java
- src/main/java/com/alkemy/ong/ports/input/rs/api/UserApi.java
- src/main/java/com/alkemy/ong/ports/input/rs/controller/UserController.java
- src/main/java/com/alkemy/ong/ports/input/rs/mapper/UserControllerMapper.java
- src/main/java/com/alkemy/ong/ports/input/rs/request/UpdateUserRequest.java
- src/test/java/com/alkemy/ong/ports/input/rs/controller/UserControllerTest.java
Validar que el usuario pueda modificar sus propios datos
Agregué lo que me indicaste en Jira, pero creo que me falta algo o le pifié a la lógica. En el Swagger estoy logueado con el user4, pero no toma los datos sino que pone "id":0.
Probé mandando solo el json con el parámetro a modificar e igual me tira un ROLE_INVALID.
> [OT210-101] Bug fix PATCH /users/{id} 

- src/main/java/com/alkemy/ong/ports/input/rs/api/NewApi.java
COMO desarrollador
QUIERO disponer de una documentación de los endpoints de Novedades
PARA tener referencias de su funcionamiento
Se deberán documentar los diferentes endpoints especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.
> [OT210-86] Agregar documentación a Novedades

- src/main/java/com/alkemy/ong/ports/input/rs/request/CreateContactRequest.java
Para el atributo email en la clase CreateContactRequest agregar validación @Email
> [OT210-100] Email Validation
